name-template: 'Release v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: ':rocket: Features and Enhancements'
    labels:
      - 'feature'
      - 'enhancement'
  - title: ':bug: Bug Fixes'
    label: 'fix'
  - title: ':wrench: Maintenance'
    labels:
      - 'chore'
  - title: ':page_facing_up: Documentation'
    label: 'Documentation'
change-template: '- $TITLE (#$NUMBER) - @$AUTHOR'
exclude-contributors:
  - 'dependabot'
  - 'dependabot[bot]'
exclude-labels:
  - 'dependencies'
  - 'chore'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |-
  ## Changes
  $CHANGES
  
  This release was made possible thanks to $CONTRIBUTORS