name: Compile

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: ${{ matrix.board.fqbn }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        board:
          - fqbn: esp8266:esp8266:generic

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile Firmware
        uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.board.fqbn }}
          platforms: |
            - name: esp8266:esp8266
              source-url: http://arduino.esp8266.com/stable/package_esp8266com_index.json
          sketch-paths: src/
          cli-compile-flags: |
            - --export-binaries

      - name: Draft Release
        if: ${{ github.event_name == 'push' }}
        id: draft-release
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        if: ${{ github.event_name == 'push' }}
        run: |
          zip ESP01Firmware.zip src/ESP01Firmware/build/esp8266.esp8266.generic/ESP01Firmware.ino.bin
          gh release upload ${{ steps.draft-release.outputs.tag_name }} ESP01Firmware.zip --clobber

